### ISSUE TITLE
Crash when using Rubidium

### ISSUE THREAD

**Issue by DJChaos42** [Tfarcenim/Enchanted-Book-Redesign#12] opened 2023-08-23 00:03 UTC
Details
---
When using the mod alongside Rubidium, the game crashes whenever an enchanted book would be on screen.

Testing Environment
---
Minecraft Version: 1.20.1

Forge Version: 47.1.44

Installed mods:
* rubidium-mc1.20.1-0.7.0a
* enchantedbookredesign-1.20.1-1

Crash Report
---
[crash-2023-08-22_17.51.07-client.txt](https://github.com/Tfarcenim/Enchanted-Book-Redesign/files/12413807/crash-2023-08-22_17.51.07-client.txt)

Relevant Log Information
---
[crash_log.txt](https://github.com/Tfarcenim/Enchanted-Book-Redesign/files/12413819/crash_log.txt)

**Comment by Tfarcenim** [comment] 2023-08-31 00:15
Duplicate of #11

**Closed as completed by Tfarcenim** 2023-08-31 00:15 UTC
